# Generated by Django 3.2.2 on 2021-05-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('poster', models.ImageField(blank=True, upload_to='')),
                ('link', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=80)),
                ('uploadDate', models.DateTimeField(auto_now_add=True)),
                ('releaseDate', models.DateField(blank=True)),
                ('genres', models.CharField(blank=True, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='SeriesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('poster', models.ImageField(blank=True, upload_to='')),
                ('link', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=80)),
                ('uploadDate', models.DateTimeField(auto_now_add=True)),
                ('releaseDate', models.DateField(blank=True)),
                ('genres', models.CharField(blank=True, max_length=70)),
            ],
        ),
    ]
