# Generated by Django 3.2.2 on 2021-05-09 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieDetails',
            new_name='MovieDetail',
        ),
        migrations.RenameModel(
            old_name='SeriesDetails',
            new_name='SeriesDetail',
        ),
    ]
