# Generated by Django 3.2.2 on 2021-05-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20210509_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetail',
            name='description',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='moviedetail',
            name='genres',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='seriesdetail',
            name='description',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='seriesdetail',
            name='genres',
            field=models.CharField(blank=True, max_length=90),
        ),
    ]
