

const FeelingLuckyActionType = {
    FEELINGLUCKY_REQUEST : 'FEELINGLUCKY_REQUEST',
    FEELINGLUCKY_SUCCESS : 'FEELINGLUCKY_SUCCESS',
    FEELINGLUCKY_FAIL : 'FEELINGLUCKY_FAIL',

}


export default FeelingLuckyActionType