# Generated by Django 3.2.2 on 2021-05-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210509_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesdetail',
            name='cureentSeason',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='seriesdetail',
            name='totlaSeason',
            field=models.IntegerField(default=1),
        ),
    ]
