# Generated by Django 3.2.2 on 2021-05-09 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20210509_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seriesdetail',
            old_name='cureentSeason',
            new_name='currentSeason',
        ),
        migrations.RenameField(
            model_name='seriesdetail',
            old_name='totlaSeason',
            new_name='totalSeason',
        ),
    ]
